homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.9475
  longitude: 0.1355
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 97
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  enable:
    - homekit

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

wemo:

ios:

device_tracker:
  - platform: tile
    username: !secret pj_email
    password: !secret tile_pj_password
  - platform: tile
    username: !secret cj_email
    password: !secret tile_cj_password

input_boolean:
  eve:
    name: Front Door
    initial: off
    icon: mdi:door

homekit:
  filter:
    exclude_domains:
      - light

sensor:
  - platform: yr
  - platform: uk_transport
    app_id: !secret transport_app_id
    app_key: !secret transport_app_key
    queries:
      - mode: train
        origin: SST
        destination: LST

media_player:
  - platform: samsungtv
    host: 192.168.1.89
    port: 8001
    name: Living Room TV

